# Generated by Django 4.2.28 on 2026-02-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubject',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
