# Generated by Django 4.2.29 on 2026-03-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='visit_category',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_category',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='subjects.subject'),
        ),
    ]
