# Generated by Django 4.2.29 on 2026-03-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('visits', '0002_historicalvisit_visit_category_visit_visit_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('screening', 'Screening'), ('baseline', 'Baseline'), ('followup', 'Follow-up'), ('unscheduled', 'Unscheduled')], max_length=50)),
                ('visit_number', models.PositiveIntegerField()),
                ('days_from_baseline', models.IntegerField()),
                ('window_before', models.IntegerField(default=0)),
                ('window_after', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('is_unscheduled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedule', to='projects.project')),
            ],
            options={
                'ordering': ['visit_number'],
                'unique_together': {('project', 'visit_number')},
            },
        ),
    ]
