# Generated by Django 4.2.29 on 2026-03-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_projectvisitschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvisitschedule',
            name='recurrence_months',
            field=models.PositiveIntegerField(default=0, help_text='0 = manual scheduling, 1 = monthly, 2 = every 2 months'),
        ),
    ]
