# Generated by Django 4.2.29 on 2026-03-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_projectvisitschedule_recurrence_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('window_open', 'Window Open'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('window_open', 'Window Open'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
