# Generated by Django 4.2.29 on 2026-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
