# Generated by Django 4.2.29 on 2026-03-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='descriptions',
            new_name='description',
        ),
    ]
