# Generated by Django 4.2.29 on 2026-03-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_created_at_country_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Countries'},
        ),
    ]
