# Generated by Django 4.2.29 on 2026-04-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
