# Generated by Django 4.2.29 on 2026-03-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_created_at_branch_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branches'},
        ),
    ]
