# Generated by Django 4.2.29 on 2026-04-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
