# Generated by Django 4.2.28 on 2026-02-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_is_active'),
        ('visits', '0001_initial'),
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalformresponse',
            name='visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='historicalformfielddefinition',
            name='form',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms_builder.formdefinition'),
        ),
        migrations.AddField(
            model_name='historicalformfielddefinition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformdefinition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformdefinition',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='historicalfieldvalue',
            name='field',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms_builder.formfielddefinition'),
        ),
        migrations.AddField(
            model_name='historicalfieldvalue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfieldvalue',
            name='response',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms_builder.formresponse'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.formdefinition'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='formfielddefinition',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.formdefinition'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.formfielddefinition'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.formresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('visit', 'form')},
        ),
        migrations.AlterUniqueTogether(
            name='formdefinition',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('response', 'field')},
        ),
    ]
