# Generated by Django 4.2.29 on 2026-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalformresponse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
