# Generated by Django 4.2.29 on 2026-03-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('forms_builder', '0002_formresponse_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittypeformassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_assignments', to='forms_builder.formdefinition'),
        ),
        migrations.AlterField(
            model_name='visittypeformassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_form_assignments', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='visittypeformassignment',
            unique_together={('project', 'visit_type', 'form')},
        ),
    ]
