# Generated by Django 4.2.29 on 2026-03-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_alter_visittypeformassignment_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.formresponse'),
        ),
    ]
