# Generated by Django 4.2.29 on 2026-03-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0004_alter_fieldvalue_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfieldvalue',
            old_name='response',
            new_name='form_response',
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='form_response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='forms_builder.formresponse'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('form_response', 'field')},
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='response',
        ),
    ]
