# Generated by Django 4.2.29 on 2026-03-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0005_rename_response_historicalfieldvalue_form_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_builder.formfielddefinition'),
        ),
    ]
