# Generated by Django 4.2.29 on 2026-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0006_alter_fieldvalue_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalformfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=20),
        ),
    ]
